"""Adicionando Pedido e PedidoProduto com seus relacionamentos

Revision ID: dd0da45d2932
Revises: eb44d3c31ec7
Create Date: 2025-04-26 17:40:43.158811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0da45d2932'
down_revision = 'eb44d3c31ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=255), nullable=False),
    sa.Column('cpf_cliente', sa.String(length=14), nullable=False),
    sa.Column('endereco_entrega', sa.String(length=500), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('email_pedido', sa.String(length=120), nullable=True),
    sa.Column('qtd_total', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    # ### end Alembic commands ###
