"""Cria tabela produto

Revision ID: eb44d3c31ec7
Revises: 0624517c11b5
Create Date: 2025-04-26 16:57:57.769048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb44d3c31ec7'
down_revision = '0624517c11b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
